### ISSUE TITLE
https://vaadin.com/directory/component/vaadin-ga-tracker = 404

### ISSUE THREAD

**Issue by marcoebbinghaus** [samie/vaadin-ga-tracker#15]
The **README.md** says 

> Official releases of this add-on are available at Vaadin Directory. For Maven instructions, download and reviews, go to http://vaadin.com/addon/vaadin-ga-tracker

The link seems to be invalid as it resolves a HTTP 404 error. So it is unclear how to use this addon in e.g. a maven based project (Vaadin 10+).

It seems like the correct link is: https://vaadin.com/directory/component/googleanalyticstracker

**Comment by samie** [comment]
Sorry about that one. I updated the links in all branches. You can use version 4.0.0 for a Vaadin 10+ project. Get dependency snippet here:  https://vaadin.com/directory/component/googleanalyticstracker/4.0.0
