### ISSUE TITLE
dynamic value 

### ISSUE THREAD

**Issue by burakkyilmaz** [samie/vaadin-ga-tracker#21]
Hello, first of all thanks for the plugin butI have some problems on version14.
 The project will be used in different sites so
@enablegoogleanalytics(value = "xxxxyyyy") 
I was unable to put this annotation value from outside(inject). I am having trouble because everyone's google analytics value is different. So is there anyway to make it dynamic?
Do you have any suggestions?

**Comment by Legioth** [comment]
You can make the class implement `TrackerConfigurator` and then give a dynamic value using `config.setTrackingId(someTrackingId)`.

**Comment by burakkyilmaz** [comment]
I think there is a bug . GoogleAnalyticsTracker 142 line 

` config=TrackerConfiguration.create(logLevel, sendHits);`

should be changed this way. (Version 4.0.0)

this way, as long as "@EnableGoogleAnalytics" isn't there, the config file comes as null.

I can open a pull request if you want.It fails the way you say

**Comment by burakkyilmaz** [comment]
"@EnableGoogleAnalytics" and `config.setTrackingId (someTrackingId) ` work properly together. I should be able to use this without annotation. I think it's the error described above

**Comment by Legioth** [comment]
In case someone else wonders, this is already fixed through https://github.com/samie/vaadin-ga-tracker/commit/698881a78ea4a38128412e6db3541405606c1266 but the fix has not yet been released.

**Comment by borax1974** [comment]
Is a new release planned in the near future?

**Comment by samie** [comment]
Just released 4.0.1 in Vaadin Directory. Sorry for the long wait!

https://vaadin.com/directory/component/googleanalyticstracker/4.0.1
