### ISSUE TITLE
Use of unsecure (http) vaadin-addons and vaadin-prerelease repositories

### ISSUE THREAD

**Issue by svenfrauen** [samie/vaadin-ga-tracker#25]
The addon still uses unsecure http repositories for vaadin-addons and vaadin-prerelease.
This happens due to the use of the Vaadin Platform (Bill of Materials) version 10.0.0 (see following screenshot).

<img width="961" alt="Bildschirmfoto 2022-01-06 um 18 25 13" src="https://user-images.githubusercontent.com/924991/148430013-e6547a56-e371-4026-a399-4a997e171d7f.png">

Since Maven 3.8.1 http repositories are blocked. So any project with this maven version or higher cannot build a project containing this addon (see following screenshot).

<img width="1775" alt="Bildschirmfoto 2022-01-06 um 17 08 58" src="https://user-images.githubusercontent.com/924991/148430083-18223409-a4eb-400e-a6c9-c1365ae13c81.png">

Could you please release a newer version with updated dependencies?

**Comment by jcgueriaud1** [comment]
This issue has been fixed in version 4.0.2.

@samie I tested the new version and the application can be built with Maven 3.8.

You can close this ticket, thanks

**Comment by samie** [comment]
Great! Thanks for testing.
