### ISSUE TITLE
Vaadin 23 and GA4

### ISSUE THREAD

**Issue by simasch** [samie/vaadin-ga-tracker#28]
Should this addon work with Vaadin 23 and GA4?

I can't find the tracking ID in the browser developer console.

**Comment by samie** [comment]
Need to have look, I haven't tested with V23 myself.

**Comment by simasch** [comment]
@samie Have you had time to have a look?

**Comment by FDelporte** [comment]
Hi, I have same question for 24-alpha...

i added this but doesn't seem to add any GA-code in the application.

```
@EnableGoogleAnalytics(value = "G-XXX")
public class MainLayout extends AppLayout {
```

**Comment by furfreemi** [comment]
Hi! We're also running into this issue- it appears that our new GA4 tag + Vaadin 23 is not compatible with this addon. We're not seeing analytics come through, and are seeing console logs of `analytics.js:21 The tracking Id should only be of the format UA-NNNNNN-N` when debugging analytics.

I believe Universal Analytics will stop processing data on July 1, 2023 in favor of GA4 tags - will this add-on be compatible with GA4 by that time?

**Comment by samie** [comment]
Had a look at this this. Looks like the changes are not that big for V23 since the GA4 is similar to the previous version. The debug configuration has changed, and older Vaadin versions need more work.

**Comment by darmro** [comment]
Hi Samie. First of all thank you for this plugin, it is very useful! And I would like to contribute to the votes that support for GA4 is really needed :)

**Comment by samie** [comment]
There are now version 4.1.0 and 5.0.0 available using the new GA4 API: https://vaadin.com/directory/component/googleanalyticstracker
