### ISSUE TITLE
Replace executeJavascript with executeJs 

### ISSUE THREAD

**Issue by javier-godoy** [samie/vaadin-ga-tracker#29]
`executeJavascript` (called by `GoogleAnalyticsTracker`) has been deprecated in Vaadin 14 and was removed in Vaadin 24.0.0.alpha10

This change would require a new major version of the add-on (or some reflection trick), since the latest one is compatible with Vaadin 10 to 23.

**Comment by samie** [comment]
Would make sense to do a major version. There are other updates needed also.

**Comment by samie** [comment]
Hi! Released version 5.0.0 for V24 with this change: https://vaadin.com/directory/component/googleanalyticstracker/5.0.0
