### ISSUE TITLE
GoogleAnalyticsTracker is not serializable

### ISSUE THREAD

**Issue by javier-godoy** [samie/vaadin-ga-tracker#33]
Ditto.
https://github.com/samie/vaadin-ga-tracker/blob/ce0b932d5f5081cde5e67e68c76acef9bcdbd45f/addon/src/main/java/org/vaadin/googleanalytics/tracking/GoogleAnalyticsTracker.java#L35

An instance of `GoogleAnalyticsTracker` is added into the UI here:
https://github.com/samie/vaadin-ga-tracker/blob/ce0b932d5f5081cde5e67e68c76acef9bcdbd45f/addon/src/main/java/org/vaadin/googleanalytics/tracking/GoogleAnalyticsTracker.java#L79-L82

**Comment by samie** [comment]
Thanks, this was purely an oversight. Do you know an easy test case we could have for this?

**Comment by javier-godoy** [comment]
I usually [have a test](https://github.com/FlowingCode/EnhancedTabs/blob/f0c8e56d88b58d14c56907ef00ba58e33e153f3c/src/test/java/com/flowingcode/vaadin/addons/enhancedtabs/test/SerializationTest.java)  to ensure that a given class is serializable.  This approach isn't perfect since (I'm lazy and) in most cases I'm just testing whether a new instance of the class can be serialized (that's likely the case, because unserializable fields are null, but it has catched some issues). More complex cases ([here](https://github.com/FlowingCode/XTermConsoleAddon/blob/018e3a36d62bad45d3388fb5e86569b5674df598/src/test/java/com/flowingcode/vaadin/addons/xterm/test/SerializationTest.java), [here](https://github.com/FlowingCode/GridExporterAddon/pull/90#pullrequestreview-1842087925)) require explicit handling, but at least they serve as regression tests.
