### ISSUE TITLE
sample code for Events tracking mentions Universal Tracking API but gives no explanation

### ISSUE THREAD

**Issue by alexeyOnGitHub** [samie/vaadin-ga-tracker#7]
```
        // Use this if you still haven't upgraded to Universal tracking API
        // tracker.setUniversalTracking(false);
```

is this "universal api" something that users of this JAR dependency need to configure somewhere? in their Google Analytics Accounts? in their web.xml? somewhere else?
my impression was that the library (JAR file) itself manages what js file is used to track pages or events.
maybe it makes sense to mention that in the file.

UPDATE:
I found that my events were not shown in GoogleAnalytics because of a filter I had. pilot error :)
feel free to close this issue.

awesome plugin!

**Comment by samie** [comment]
Ok. Will close.

Universal Analytics is the "new"  Google tracking and default already for few years. More details about it: https://developers.google.com/analytics/devguides/collection/upgrade/
